# -*- coding: utf-8 -*-
"""assignment_1

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Xx8Z_Y4Sh4cWUf4uNxVH3DI6Iuoe2iDs
"""

ame_price = 3500
cafe_price = 4000
ame = 2
cafe = 2

total1 = ame_price*ame+cafe_price*cafe
print(total1)

ame_price = 3500
va_price = 4300
ain_price = 5000
ame = 3
va = 4
ain = 2

total2 = int((ame_price*ame+va_price*va+ain_price*ain)*90/100)
print(total2)